#!/bin/bash
#SBATCH --time=08:00:00
#SBATCH --nodes=1
#SBATCH -A guowei-search
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --constraint="amd20"
#SBATCH --mem=40G
#SBATCH --job-name 1A5E_A_L_37_S
#SBATCH --output=./feat_out/1A5E_A_L_37_S.out
cd /mnt/research/guowei-search.4/junjie-proteng/S2648/features/1A5E_A_L_37_S
module purge
module load GCC/12.3.0 OpenMPI/4.1.5-GCC-12.3.0
python feature.py 1A5E A A L 37 S 8.5
python feature_Lap.py 1A5E A A L 37 S 8.5
